.SILENT:

# Colours:
BLACK = 0
RED   = 1
GREEN = 2
YELLOW = 3
BLUE  = 4
MAGENTA = 5
CYAN  = 6
WHITE = 7

# OK and FAIL messages (with colour)
OK = echo "Tests in '$(CURDIR)': $(shell tput setaf $(GREEN))Ok$(shell tput sgr0)"
FAIL = echo "Tests in '$(CURDIR)': $(shell tput setaf $(RED))Failed$(shell tput sgr0)"

VERIFY = cmp output expected ; \
	if [ $$? -ne 0 ] ; then \
		$(FAIL) ; \
		diff output expected ; \
		exit 1 ; \
	else \
		$(OK) ; \
		exit 0 ; \
	fi
